hybrid_retriever:
  persist_dir: "./data/chroma_embeddings"
  collection: "election_data"
  top_k: 5
  semantic_weight: 0.7
  keyword_weight: 0.3

llm:
  llm_model: "openai"
  embedding_model: "text-embedding-3-small" 

defaults:
  - _self_
  - response_prompt