crawler:
  url: "https://www.pap.org.sg/category/featured/"
  raw_md_dir: "./data/crawled_data/raw_md"
  extracted_dir: "./data/crawled_data/extracted"
  file_name: "pap_constituency"
  crawl_enabled: false
  use_existing_json: false
  extract_json_enabled: false
  llm: "openai:gpt-4.1-mini"


graphdb:
  enabled: true
  clear_before_import: true

defaults:
  - _self_
  - extract_crawl_prompts